# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LMPageContrllerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.1'
  pod 'LMPageController', :path => '../'
  pod 'RxSwift', '~> 5.0.0'
  pod 'MJRefresh', '~> 3.2.0'

  # Pods for LMPageContrllerExample

  target 'LMPageContrllerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
